In [1]:
import numpy as np

# This is the code

In [58]:
import sklearn as sk

In [59]:
a=np.arange(5)

In [66]:
b=np.arange(5)+1

In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
a*b

array([ 0,  2,  6, 12, 20])

In [69]:
a@b

40

In [70]:
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [73]:
a = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
np.savetxt("foo.csv", a, delimiter=",")

In [77]:
from numpy import random
random_num=random.randint(100,size=(5))

In [78]:
print(random_num)

[41  3 81 43 95]
